# Go Tunnel Server Configuration
# 服务端配置文件

port: 3339  # Server listen port / 服务端监听端口
pool_size: 20  # Proxy connection pool size / 代理连接池大小
connect_timeout: 60  # Connection timeout in seconds / 连接超时时间（秒）

# User authentication / 用户认证
users:
  - username: admin
    password: "123456"
  # Add more users as needed / 根据需要添加更多用户
  # - username: user2
  #   password: "password2"

# Logging configuration / 日志配置
log:
  enable: true  # Enable logging / 启用日志
  path: logs    # Log directory / 日志目录